NMRAnalysis:	NMRAnalysis.C
	g++ -o NMRAnalysis NMRAnalysis.C `root-config --cflags --libs`
AbsProbeAnalysis:	AbsProbeAnalysis.C
	g++ -o AbsProbeAnalysis AbsProbeAnalysis.C `root-config --cflags --libs`
