#!/bin/bash

# CernVM-FS
if [ -e /cvmfs/gm2.opensciencegrid.org/prod ]
then
	echo "Sourcing g-2 UPS environment setup."
	source /cvmfs/gm2.opensciencegrid.org/prod/g-2/setup >& /dev/null
	setup root v5_34_25 -q e7:prof
	setup boost v1_57_0 -q e7:prof
	setup zmq v4_1_5 -q e7:prof
else
	echo "CVMFS not mounted."
fi
